[[main]]
name = "home"
pageRef = ""
identifier = "EROAXPnuMj"
weight = 1

[[main]]
name = "projects"
pageRef = "projects"
identifier = "2jOMxSC9At"
weight = 2

[[main]]
name = "resume"
pageRef = "portfolio"
identifier = "NGSdgIHFBb"
weight = 3

[[footer]]
none = "none"
