
[[main]]
name = "Home"
url = "https://simplynarwall.github.io/Portfolio/"
weight = 1


[[main]]
name = "Projects"
pageRef = "projects"
identifier = "2jOMxSC9At"
weight = 2

[[main]]
name = "Resume"
pageRef = "resume"
identifier = "NGSdgIHFBb"
weight = 3

[[footer]]
none = "none"
